### PR TITLE
Update rover.s2e

### PR DESCRIPTION
**Pull request by sauravlaxman**
This is just a trial to see if my tv remote can work with arduino using mblock.

### CODE REVIEW

**Comment by Ahmedfcis** [comment]
Thank you Sourav, But I think we need a generic solution to support other remote types. I think we can add other functions (eg.  "Is Remote Key With Code %d Pressed" , "Is Remote Key With Code %d Released") or support the existing function to take the code as input rather than the list values.

**Comment by hasankemer** [comment]
Please update . 
Because we use this extension with another  ir remote

**Comment by Ahmedfcis** [comment]
@hasankemer , I tested the extension, first you can use any number value in **Is Remote (_123456_) Key Pressed** block. If that works on your side. so your problem will be only to get the valid codes for your remote.

I added [src.ino](https://github.com/Ahmedfcis/mBlock_Arduino_Rover/blob/master/mblock_ext/src/src.ino) file. It's an arduino code to print the pressed remote key

**Comment by hasankemer** [comment]
Bro thank you very much.
I will try 3 day ago

**Comment by hasankemer** [comment]
3 day later 😂

**Pull request closed without merging**
